import Head from "next/head";
import AdminNav from "./AdminNav";
import { ReactNode } from "react";


interface AdminLayoutProps {
    children: ReactNode;
    title: string;
}



export default function AdminLayout({ children, title }: AdminLayoutProps) {
    return (
        <>
          <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
            <div className="flex h-[100vh]">
                <AdminNav/> 
                <main className="p-6 ">{children}</main>
            </div>
         
    
          
         
        </>
      );
    };

